# Generated by Django 6.1.1 on 2026-09-13 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('legal_name', models.CharField(help_text='Registered legal company name.', max_length=255)),
                ('trade_name', models.CharField(blank=True, help_text="Public-facing brand name, e.g. 'ARKO'.", max_length=255)),
                ('registration_number', models.CharField(help_text='Commercial/trade registry number.', max_length=100)),
                ('vat_number', models.CharField(max_length=50, verbose_name='TVA / VAT number')),
                ('street', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=100)),
                ('postal_code', models.CharField(max_length=20)),
                ('country', models.CharField(choices=[('DE', 'Germany'), ('FR', 'France'), ('IT', 'Italy'), ('ES', 'Spain'), ('NL', 'Netherlands'), ('AT', 'Austria'), ('BE', 'Belgium'), ('CH', 'Switzerland'), ('PT', 'Portugal'), ('PL', 'Poland'), ('SE', 'Sweden'), ('NO', 'Norway'), ('DK', 'Denmark'), ('GB', 'United Kingdom')], default='DE', max_length=2)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=30)),
                ('website', models.URLField(blank=True)),
                ('bank_name', models.CharField(blank=True, max_length=150)),
                ('iban', models.CharField(blank=True, max_length=34)),
                ('bic_swift', models.CharField(blank=True, max_length=11, verbose_name='BIC / SWIFT')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='company/')),
                ('invoice_footer_note', models.TextField(blank=True, help_text='Free-text note printed at the bottom of invoices/receipts (e.g. legal disclaimers).')),
                ('default_currency', models.CharField(default='EUR', max_length=3)),
                ('default_vat_rate', models.DecimalField(decimal_places=2, default=19.0, help_text='Fallback VAT rate used when the destination country has no explicit VATRate row.', max_digits=5)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Company Information',
                'verbose_name_plural': 'Company Information',
            },
        ),
        migrations.CreateModel(
            name='VATRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(choices=[('DE', 'Germany'), ('FR', 'France'), ('IT', 'Italy'), ('ES', 'Spain'), ('NL', 'Netherlands'), ('AT', 'Austria'), ('BE', 'Belgium'), ('CH', 'Switzerland'), ('PT', 'Portugal'), ('PL', 'Poland'), ('SE', 'Sweden'), ('NO', 'Norway'), ('DK', 'Denmark'), ('GB', 'United Kingdom')], max_length=2, unique=True)),
                ('rate_percent', models.DecimalField(decimal_places=2, help_text='e.g. 19.00 for 19%', max_digits=5)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'VAT Rate',
                'verbose_name_plural': 'VAT Rates',
                'ordering': ['country'],
            },
        ),
    ]
