# Generated by Django 6.1.1 on 2026-09-16 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_algeria_wilaya_and_brand'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyinfo',
            name='tagline',
            field=models.CharField(blank=True, help_text='Short brand line used in page meta descriptions and the footer.', max_length=255),
        ),
    ]
