"""
Sales receiving account on CompanyInfo, for BaridiMob / CCP transfers.

These are the destination details a customer types into their banking app
to pay us, so unlike the bank_name/iban/bic_swift block (the company's own
banking identity, printed on invoices) they are rendered mid-checkout and
into the payment-instructions email.

All blank by default rather than seeded with a placeholder: a wrong RIP
sends real customer money to the wrong account, so the BaridiMob option
stays hidden at checkout until a real one is entered in the admin (see
CompanyInfo.has_sales_account and orders.forms.CheckoutPaymentForm).
"""

# Generated by Django 6.1.1 on 2026-09-16 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_companyinfo_tagline'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyinfo',
            name='sales_account_holder',
            field=models.CharField(blank=True, help_text='Name the account is registered under, exactly as it appears to the sender.', max_length=255),
        ),
        migrations.AddField(
            model_name='companyinfo',
            name='sales_bank_name',
            field=models.CharField(blank=True, help_text='Bank or institution holding the sales account (e.g. Algérie Poste, BNA).', max_length=150),
        ),
        migrations.AddField(
            model_name='companyinfo',
            name='sales_ccp_number',
            field=models.CharField(blank=True, help_text='CCP account number including its 2-digit key (e.g. 1234567 89).', max_length=25, verbose_name='Sales CCP number'),
        ),
        migrations.AddField(
            model_name='companyinfo',
            name='sales_payment_email',
            field=models.EmailField(blank=True, help_text='Where customers send payment proof if the upload fails. Falls back to settings.ADMIN_NOTIFICATION_EMAIL when empty.', max_length=254),
        ),
        migrations.AddField(
            model_name='companyinfo',
            name='sales_payment_note',
            field=models.TextField(blank=True, help_text='Optional extra instructions shown under the transfer details (e.g. what reference to put on the transfer).'),
        ),
        migrations.AddField(
            model_name='companyinfo',
            name='sales_rip',
            field=models.CharField(blank=True, help_text='20-digit RIP used for BaridiMob transfers. Shown to customers at checkout.', max_length=25, verbose_name='Sales RIP (BaridiMob)'),
        ),
    ]
