# Generated by Django 6.1.1 on 2026-09-17 06:14

import core.constants
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_baridimob_payment_proof'),
    ]

    operations = [
        migrations.CreateModel(
            name='CheckoutSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('free_shipping_threshold', models.DecimalField(decimal_places=2, default=Decimal('150000.00'), help_text="Orders at or above this subtotal (DZD) ship free, whichever delivery method was chosen. Set it high enough that it doesn't swallow every order.", max_digits=12)),
                ('standard_shipping_fee', models.DecimalField(decimal_places=2, default=Decimal('800.00'), help_text='Flat home-delivery fee (DZD) used for wilayas with no Shipping Zone row of their own.', max_digits=10)),
                ('express_shipping_surcharge', models.DecimalField(decimal_places=2, default=Decimal('700.00'), help_text='Added on top of the home-delivery fee for Express. Never charged on a free-shipping order.', max_digits=10)),
                ('card_payments_enabled', models.BooleanField(default=False, help_text="Off until Chargily has verified the account and CHARGILY_KEY/CHARGILY_SECRET are set. While off, the card option is shown at checkout as 'coming soon' and cannot be selected (server-side too, not just visually).", verbose_name='CIB / Edahabia card payments enabled')),
                ('card_payments_unavailable_note', models.CharField(blank=True, default='Card payments are coming soon — please use one of the options below.', help_text='Shown under the greyed-out card option while card payments are disabled.', max_length=255)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Checkout Settings',
                'verbose_name_plural': 'Checkout Settings',
            },
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='Language code, e.g. "fr", "ar", "kab".', max_length=5, unique=True)),
                ('name', models.CharField(help_text='Name shown in the selector, in that language.', max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.PositiveSmallIntegerField(default=0, help_text='Lower numbers appear first in the selector.')),
            ],
            options={
                'ordering': ['sort_order', 'code'],
            },
        ),
        migrations.CreateModel(
            name='Wilaya',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='Official 2-digit wilaya code (01-58) as used by the courier networks.', max_length=2, unique=True)),
                ('name', models.CharField(help_text='Display name shown in dropdowns.', max_length=100)),
                ('is_active', models.BooleanField(default=True, help_text='Uncheck to withdraw this wilaya from every dropdown without deleting it (existing orders keep resolving its name).')),
            ],
            options={
                'verbose_name': 'Wilaya',
                'verbose_name_plural': 'Wilayas',
                'ordering': ['code'],
            },
        ),
        migrations.AlterField(
            model_name='companyinfo',
            name='wilaya',
            field=models.CharField(choices=core.constants.wilaya_choices, default='16', max_length=2),
        ),
        migrations.AlterField(
            model_name='shippingzone',
            name='wilaya',
            field=models.CharField(choices=core.constants.wilaya_choices, max_length=2, unique=True),
        ),
        migrations.AlterField(
            model_name='vatrate',
            name='wilaya',
            field=models.CharField(choices=core.constants.wilaya_choices, max_length=2, unique=True),
        ),
    ]
