# Generated by Django 6.1.1 on 2026-09-13 09:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        ('dealers', '0001_initial'),
        ('orders', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(blank=True, help_text='e.g. "Home", "Work".', max_length=50)),
                ('street', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=100)),
                ('postal_code', models.CharField(max_length=20)),
                ('country', models.CharField(choices=[('DE', 'Germany'), ('FR', 'France'), ('IT', 'Italy'), ('ES', 'Spain'), ('NL', 'Netherlands'), ('AT', 'Austria'), ('BE', 'Belgium')], max_length=2)),
                ('is_default', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Addresses',
                'ordering': ['-is_default', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='GarageEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vin', models.CharField(max_length=17, unique=True, verbose_name='VIN')),
                ('warranty_active', models.BooleanField(default=True)),
                ('service_due_at', models.DateField(blank=True, null=True)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('order_item', models.ForeignKey(blank=True, help_text='Links this entry back to the purchase that created it, if any.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='garage_entry', to='orders.orderitem')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='garage_entries', to='catalog.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='garage_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Garage Entries',
                'ordering': ['-added_at'],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('customer', 'Customer'), ('dealer_staff', 'Dealer Staff'), ('admin', 'Store Administrator')], default='customer', max_length=20)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('preferred_language', models.CharField(choices=[('en', 'English'), ('de', 'Deutsch'), ('fr', 'Français'), ('it', 'Italiano'), ('es', 'Español')], default='en', max_length=5)),
                ('marketing_opt_in', models.BooleanField(default=True, help_text='Product updates / news — on by default.')),
                ('order_notifications_opt_in', models.BooleanField(default=True, help_text='Order notifications — on by default.')),
                ('promo_opt_in', models.BooleanField(default=False, help_text='Promotional offers — off by default.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('dealer', models.ForeignKey(blank=True, help_text='Required when role = Dealer Staff (BR-ACC-04); booking-queue access is scoped to this dealer only.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='staff_profiles', to='dealers.dealer')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
