# Generated by Django 6.1.1 on 2026-09-17 06:14

import core.constants
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_address_wilaya'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='wilaya',
            field=models.CharField(choices=core.constants.wilaya_choices, max_length=2),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='preferred_language',
            field=models.CharField(choices=core.constants.language_choices, default='fr', max_length=5),
        ),
    ]
