# Generated by Django 6.1.1 on 2026-09-13 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dealer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('slug', models.SlugField(blank=True, max_length=170, unique=True)),
                ('city', models.CharField(max_length=100)),
                ('country', models.CharField(choices=[('DE', 'Germany'), ('FR', 'France'), ('IT', 'Italy'), ('ES', 'Spain'), ('NL', 'Netherlands'), ('AT', 'Austria'), ('BE', 'Belgium'), ('CH', 'Switzerland'), ('PT', 'Portugal'), ('PL', 'Poland'), ('SE', 'Sweden'), ('NO', 'Norway'), ('DK', 'Denmark'), ('GB', 'United Kingdom')], max_length=2)),
                ('address', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=30)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('hours', models.CharField(help_text='Human-readable opening hours.', max_length=255)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
