# Generated by Django 6.1.1 on 2026-09-17 06:14

import core.constants
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dealers', '0002_dealer_wilaya'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dealer',
            name='wilaya',
            field=models.CharField(choices=core.constants.wilaya_choices, max_length=2),
        ),
    ]
