"""
Optional product video on the detail page.

`video_file` (an upload) joins the `video_trailer_url` that already
existed on the model but was never rendered anywhere. Two fields because
a shop either has the film hosted already (YouTube/Vimeo link) or has the
file in hand and nowhere to put it; `video_poster` is the still shown
before an uploaded file plays. Product.video_source decides which one
wins when both are set.

Additive and blank-by-default throughout -- no existing product changes,
and a catalogue with no videos renders exactly as it did before.
"""

# Generated by Django 6.1.1 on 2026-09-17 07:46

import catalog.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_compare_compareitem_wishlist_wishlistitem_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='video_file',
            field=models.FileField(blank=True, help_text='Motorcycles only. Optional. MP4 or WebM, under 200 MB. Takes precedence over the link above.', upload_to=catalog.models.product_video_upload_to, validators=[catalog.models.validate_product_video], verbose_name='Video file (upload)'),
        ),
        migrations.AddField(
            model_name='product',
            name='video_poster',
            field=models.ImageField(blank=True, help_text="Optional still shown before an uploaded video plays. Falls back to the product's first photo. Not used for YouTube/Vimeo, which supply their own thumbnail.", upload_to='products/video/posters/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='video_trailer_url',
            field=models.URLField(blank=True, help_text='Motorcycles only. Paste a YouTube, Vimeo, or direct video-file link. Watch, youtu.be, Shorts and embed forms are all accepted. Ignored if a video file is uploaded below.', verbose_name='Video link (YouTube / Vimeo)'),
        ),
    ]
