# Generated by Django 6.1.1 on 2026-09-13 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FinancingPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('term_months', models.PositiveSmallIntegerField(help_text='e.g. 12, 24, 36', unique=True)),
                ('apr', models.DecimalField(decimal_places=2, default=0, help_text='Annual percentage rate, e.g. 0.00 for 0%% APR.', max_digits=5)),
                ('description', models.TextField(blank=True)),
                ('zero_down_option', models.BooleanField(default=False, help_text='e.g. the 24-month plan\'s "€0-down" option.')),
                ('is_featured', models.BooleanField(default=False, help_text='Visually marked as "most popular".')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['term_months'],
            },
        ),
        migrations.CreateModel(
            name='InsuranceTier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('essential', 'Essential'), ('comprehensive', 'Comprehensive'), ('premium', 'Premium')], max_length=20, unique=True)),
                ('monthly_price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('features', models.JSONField(blank=True, default=list, help_text='Ordered list of included feature strings.')),
                ('excess_amount', models.DecimalField(blank=True, decimal_places=2, help_text='e.g. €250 excess on Comprehensive, €0 on Premium.', max_digits=8, null=True)),
                ('is_featured', models.BooleanField(default=False, help_text='Visually marked as the "popular" tier.')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['monthly_price'],
            },
        ),
    ]
