# Generated by Django 6.1.1 on 2026-09-16 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='financingplan',
            name='zero_down_option',
            field=models.BooleanField(default=False, help_text='e.g. the 24-month plan\'s "zero-down" option.'),
        ),
        migrations.AlterField(
            model_name='insurancetier',
            name='excess_amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='e.g. 37,000 DA excess on Comprehensive, 0 on Premium.', max_digits=8, null=True),
        ),
    ]
