# Generated by Django 6.1.1 on 2026-09-15 11:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutPageContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hero_eyebrow', models.CharField(default='Our Story', max_length=60)),
                ('hero_title_line1', models.CharField(default='BUILT TO BREAK', max_length=80)),
                ('hero_title_line2', models.CharField(default='THE SILENCE', max_length=80)),
                ('hero_subtitle', models.TextField(default='Founded in 2021 in Berlin, ARKO builds electric motorcycles for riders who go where the road ends. No noise. No emissions. No compromise.')),
                ('hero_image', models.ImageField(blank=True, help_text="Optional. Falls back to the flagship motorcycle's own photo when empty.", null=True, upload_to='about/')),
                ('mission_eyebrow', models.CharField(default='The Mission', max_length=60)),
                ('mission_title', models.CharField(default="Terrain Doesn't Forgive. Neither Do We.", max_length=120)),
                ('mission_paragraph_1', models.TextField(default='We started ARKO because electric motorcycles were either street scooters or expensive prototypes. We wanted a bike that could handle a hard enduro stage on Saturday and commute to work on Monday — all electric, all silent, all torque.')),
                ('mission_paragraph_2', models.TextField(default='Every ARKO is designed and assembled in our Berlin facility. We forge our own frames, wind our own motors, and test every bike on the trails of the Brandenburg forest before it ships.')),
                ('mission_paragraph_3', models.TextField(default="We believe electric is not a compromise — it's an advantage. Instant torque. Zero maintenance. Silent operation that lets you hear the trail instead of the engine.")),
                ('mission_image', models.ImageField(blank=True, help_text="Optional. Falls back to the flagship motorcycle's own photo when empty.", null=True, upload_to='about/')),
                ('stats_eyebrow', models.CharField(default='By the Numbers', max_length=60)),
                ('stats_title', models.CharField(default='ARKO in 2026', max_length=100)),
                ('riders_stat_value', models.CharField(default='15K+', max_length=20)),
                ('riders_stat_label', models.CharField(default='Riders Worldwide', max_length=40)),
                ('co2_stat_value', models.CharField(default='0g', max_length=20)),
                ('co2_stat_label', models.CharField(default='CO2 Per Km', max_length=40)),
                ('values_eyebrow', models.CharField(default='What We Believe', max_length=60)),
                ('values_title', models.CharField(default='Our Values', max_length=100)),
                ('timeline_eyebrow', models.CharField(default='The Journey', max_length=60)),
                ('timeline_title', models.CharField(default='Our Timeline', max_length=100)),
                ('team_eyebrow', models.CharField(default='The People', max_length=60)),
                ('team_title', models.CharField(default='Leadership', max_length=100)),
                ('cta_eyebrow', models.CharField(default='Join the Ride', max_length=60)),
                ('cta_title', models.CharField(default='Ready to Go Electric?', max_length=100)),
                ('cta_body', models.TextField(default='Book a test ride at your nearest dealer and feel the instant torque for yourself.')),
            ],
            options={
                'verbose_name': 'About Page Content',
                'verbose_name_plural': 'About Page Content',
            },
        ),
        migrations.CreateModel(
            name='HomePageContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hero_eyebrow', models.CharField(default='Electric Off-Road', max_length=60)),
                ('hero_title_line1', models.CharField(default='TERRAIN THAT', max_length=80)),
                ('hero_title_line2', models.CharField(default="DOESN'T FORGIVE", max_length=80)),
                ('hero_subtitle', models.TextField(default='Instant torque. Hot-swap batteries. Zero emissions. Built in Europe for riders who go where the road ends.')),
                ('hero_image', models.ImageField(blank=True, help_text="Optional. Falls back to the flagship motorcycle's own photo when empty.", null=True, upload_to='home/')),
                ('compare_eyebrow', models.CharField(default='Side by Side', max_length=60)),
                ('compare_title', models.CharField(default='Compare Models', max_length=100)),
                ('compare_body', models.TextField(default='Stack up to 4 models side by side. Compare range, power, weight, and price to find the right bike for your riding style.')),
                ('testride_eyebrow', models.CharField(default='Experience Before You Buy', max_length=60)),
                ('testride_title', models.CharField(default='Ride Before You Decide', max_length=100)),
                ('testride_body', models.TextField(default="Book a free test ride at any of our {dealer_count} European dealers. Bring your licence, we'll bring the bike.", help_text='Use the literal text "{dealer_count}" anywhere you want the live dealer count inserted.')),
            ],
            options={
                'verbose_name': 'Home Page Content',
                'verbose_name_plural': 'Home Page Content',
            },
        ),
        migrations.CreateModel(
            name='LegalDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(help_text='e.g. "terms", "privacy"', max_length=40, unique=True)),
                ('title', models.CharField(max_length=100)),
                ('last_updated', models.DateField()),
                ('body', models.TextField(help_text='Full HTML. Available merge fields: {legal_name}, {street}, {postal_code}, {city}, {country}, {vat_number}.')),
            ],
            options={
                'verbose_name': 'Legal Document',
                'ordering': ['slug'],
            },
        ),
        migrations.CreateModel(
            name='NotFoundPageContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(default='This Trail Has No End', max_length=100)),
                ('body', models.TextField(default="The page you're looking for has gone off-road and we can't find it. Let's get you back on track.")),
            ],
            options={
                'verbose_name': '404 Page Content',
                'verbose_name_plural': '404 Page Content',
            },
        ),
        migrations.CreateModel(
            name='SupportPageContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_support', models.EmailField(default='support@arko.eu', max_length=254)),
                ('email_sales', models.EmailField(default='sales@arko.eu', max_length=254)),
                ('email_response_note', models.CharField(default='Get a response within 24 hours.', max_length=120)),
                ('hours_text', models.CharField(default='Mon–Fri 9:00–18:00 CET', max_length=80)),
                ('livechat_text', models.CharField(default='Live chat available 24/7', max_length=80)),
            ],
            options={
                'verbose_name': 'Support Page Content',
                'verbose_name_plural': 'Support Page Content',
            },
        ),
        migrations.CreateModel(
            name='HomeMarqueeItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=60)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('home', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='marquee_items', to='content.homepagecontent')),
            ],
            options={
                'verbose_name': 'Marquee Item',
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='HomeHeroStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(help_text='e.g. "120 km"', max_length=30)),
                ('label', models.CharField(help_text='e.g. "Max Range"', max_length=40)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('home', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hero_stats', to='content.homepagecontent')),
            ],
            options={
                'verbose_name': 'Hero Stat',
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('role', models.CharField(max_length=100)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='team/')),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('about', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_members', to='content.aboutpagecontent')),
            ],
            options={
                'verbose_name': 'Team Member',
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='TimelineEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(max_length=10)),
                ('title', models.CharField(max_length=100)),
                ('body', models.TextField()),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('about', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timeline_events', to='content.aboutpagecontent')),
            ],
            options={
                'verbose_name': 'Timeline Event',
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ValueProp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.CharField(default='bx-bolt', help_text='Boxicons class, e.g. "bx-bolt"', max_length=40)),
                ('title', models.CharField(max_length=80)),
                ('body', models.TextField()),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('about', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='values', to='content.aboutpagecontent')),
            ],
            options={
                'verbose_name': 'Value',
                'ordering': ['sort_order', 'id'],
            },
        ),
    ]
