# Generated by Django 6.1.1 on 2026-09-15 18:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0003_seed_page_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepagecontent',
            name='battery_body',
            field=models.TextField(default='No cables, no chargers, no waiting at the trailhead. Pull the spent cell, drop in a charged one, and get back on the line.'),
        ),
        migrations.AddField(
            model_name='homepagecontent',
            name='battery_eyebrow',
            field=models.CharField(default='Field-Ready Power', max_length=60),
        ),
        migrations.AddField(
            model_name='homepagecontent',
            name='battery_image',
            field=models.ImageField(blank=True, help_text="Optional. Falls back to the flagship motorcycle's own photo when empty.", null=True, upload_to='home/'),
        ),
        migrations.AddField(
            model_name='homepagecontent',
            name='battery_title_line1',
            field=models.CharField(default='SWAP IN', max_length=60),
        ),
        migrations.AddField(
            model_name='homepagecontent',
            name='battery_title_line2',
            field=models.CharField(default='30 SECONDS.', max_length=60),
        ),
        migrations.AddField(
            model_name='homepagecontent',
            name='cine_image',
            field=models.ImageField(blank=True, help_text="Poster/background image. Falls back to the flagship motorcycle's own photo when empty.", null=True, upload_to='home/'),
        ),
        migrations.AddField(
            model_name='homepagecontent',
            name='cine_title_line1',
            field=models.CharField(default='GO WHERE', max_length=60),
        ),
        migrations.AddField(
            model_name='homepagecontent',
            name='cine_title_line2',
            field=models.CharField(default='THE ROAD ENDS.', max_length=60),
        ),
        migrations.AddField(
            model_name='homepagecontent',
            name='cine_video',
            field=models.FileField(blank=True, help_text='Optional. MP4 film played muted-loop behind the banner. When empty, cine_image is shown as a static banner instead.', null=True, upload_to='home/video/'),
        ),
        migrations.AddField(
            model_name='homepagecontent',
            name='final_cta_body',
            field=models.TextField(default="Built for riders who don't need a road to know where they're going. Reserve yours before the first production run closes."),
        ),
        migrations.AddField(
            model_name='homepagecontent',
            name='final_cta_image',
            field=models.ImageField(blank=True, help_text="Optional. Falls back to the flagship motorcycle's own photo when empty.", null=True, upload_to='home/'),
        ),
        migrations.AddField(
            model_name='homepagecontent',
            name='final_cta_title_line1',
            field=models.CharField(default='YOUR TRAIL', max_length=60),
        ),
        migrations.AddField(
            model_name='homepagecontent',
            name='final_cta_title_line2',
            field=models.CharField(default='IS WAITING.', max_length=60),
        ),
        migrations.CreateModel(
            name='HomeCarouselSlide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='home/carousel/')),
                ('caption', models.CharField(blank=True, help_text='e.g. "Studio · Front"', max_length=80)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('home', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='carousel_slides', to='content.homepagecontent')),
            ],
            options={
                'verbose_name': 'Carousel Slide',
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='HomeShowcasePanel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='home/showcase/')),
                ('title', models.CharField(help_text='e.g. "Instant torque."', max_length=60)),
                ('body', models.TextField()),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('home', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='showcase_panels', to='content.homepagecontent')),
            ],
            options={
                'verbose_name': 'Showcase Panel',
                'ordering': ['sort_order', 'id'],
            },
        ),
    ]
