# Generated by Django 6.1.1 on 2026-09-16 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0004_homepagecontent_battery_body_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='legaldocument',
            name='body',
            field=models.TextField(help_text='Full HTML. Available merge fields: {legal_name}, {trade_name}, {street}, {postal_code}, {city}, {wilaya}, {vat_number}.'),
        ),
    ]
