# Generated by Django 6.1.1 on 2026-09-16 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0005_alter_legaldocument_body'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutpagecontent',
            name='hero_subtitle',
            field=models.TextField(default='Founded in 2021 in Setif, we build electric motorcycles for riders who go where the road ends. No noise. No emissions. No compromise.'),
        ),
        migrations.AlterField(
            model_name='aboutpagecontent',
            name='mission_paragraph_1',
            field=models.TextField(default='We started this company because electric motorcycles were either street scooters or expensive prototypes. We wanted a bike that could handle a hard enduro stage on Saturday and commute to work on Monday — all electric, all silent, all torque.'),
        ),
        migrations.AlterField(
            model_name='aboutpagecontent',
            name='mission_paragraph_2',
            field=models.TextField(default='Every bike is designed and assembled in our Setif facility. We forge our own frames, wind our own motors, and test every bike in the Babor mountains before it ships.'),
        ),
        migrations.AlterField(
            model_name='aboutpagecontent',
            name='riders_stat_label',
            field=models.CharField(default='Riders Nationwide', max_length=40),
        ),
        migrations.AlterField(
            model_name='aboutpagecontent',
            name='stats_title',
            field=models.CharField(default='By the Numbers, 2026', max_length=100),
        ),
        migrations.AlterField(
            model_name='homepagecontent',
            name='hero_subtitle',
            field=models.TextField(default='Instant torque. Hot-swap batteries. Zero emissions. Built for Algerian roads and the tracks beyond them.'),
        ),
        migrations.AlterField(
            model_name='homepagecontent',
            name='testride_body',
            field=models.TextField(default="Book a free test ride at any of our {dealer_count} dealers across the country. Bring your licence, we'll bring the bike.", help_text='Use the literal text "{dealer_count}" anywhere you want the live dealer count inserted.'),
        ),
    ]
