# Generated by Django 6.1.1 on 2026-09-17 06:14

import core.constants
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimeSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(help_text='Stored on bookings, e.g. "morning". Changing it orphans existing bookings — add a new slot instead.', max_length=20, unique=True)),
                ('label', models.CharField(help_text='What the customer sees, e.g. "Morning (9:00 - 13:00)".', max_length=100)),
                ('is_active', models.BooleanField(default=True, help_text='Uncheck to stop offering this slot without deleting it.')),
                ('sort_order', models.PositiveSmallIntegerField(default=0, help_text='Lower numbers appear first on the booking forms.')),
            ],
            options={
                'ordering': ['sort_order', 'code'],
            },
        ),
        migrations.AlterField(
            model_name='servicebooking',
            name='time_slot',
            field=models.CharField(choices=core.constants.time_slot_choices, max_length=20),
        ),
        migrations.AlterField(
            model_name='testridebooking',
            name='time_slot',
            field=models.CharField(choices=core.constants.time_slot_choices, max_length=20),
        ),
    ]
