"""
BaridiMob payment method, the order's payment_state, and PaymentProof.

Adds the third payment method and the manual settlement cycle behind it:
the customer transfers to the sales account on core.CompanyInfo, uploads a
receipt (PaymentProof), and someone reviews it in the admin, with an email
at every hop. See orders/signals.py for the state transitions and
orders/notifications.py for the mail.

`payment_state` is tracked separately from Order.status because the two
answer different questions -- fulfilment versus money -- and an order can
legitimately be Processing while its payment is still Awaiting Proof. It
defaults to NOT_REQUIRED, which is also the correct value for every order
that already exists: all of them predate BaridiMob, so none of them is
waiting on a proof and no data migration is needed to say so.

Widening payment_method's choices rewrites no rows -- historic orders keep
rendering their own stored value, same as migration 0003.
"""

# Generated by Django 6.1.1 on 2026-09-16 11:14

import django.db.models.deletion
import orders.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_manual_payment_method'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_state',
            field=models.CharField(choices=[('not_required', 'Not Required'), ('awaiting_proof', 'Awaiting Payment Proof'), ('under_review', 'Proof Under Review'), ('confirmed', 'Payment Confirmed'), ('rejected', 'Proof Rejected')], default='not_required', max_length=20),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('cib', 'CIB / Edahabia Card'), ('baridimob', 'BaridiMob / CCP / Bank Transfer'), ('manual', 'Manual Order (Cash on Delivery / Bank Transfer)')], max_length=20),
        ),
        migrations.CreateModel(
            name='PaymentProof',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(help_text='Screenshot or PDF receipt of the transfer (PDF, JPG, PNG or WEBP).', upload_to=orders.models.payment_proof_upload_to, validators=[orders.models.validate_payment_proof])),
                ('original_filename', models.CharField(blank=True, editable=False, max_length=255)),
                ('amount_declared', models.DecimalField(blank=True, decimal_places=2, help_text='Amount the customer says they transferred, in DZD.', max_digits=10, null=True)),
                ('transaction_reference', models.CharField(blank=True, help_text="Transfer/transaction reference shown in the customer's banking app.", max_length=100)),
                ('sender_note', models.TextField(blank=True, help_text='Optional message from the customer.')),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('confirmed', 'Confirmed'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('review_note', models.TextField(blank=True, help_text='Shown to the customer verbatim when a proof is rejected — say what to fix.')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_proofs', to='orders.order')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_payment_proofs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Payment Proof',
                'verbose_name_plural': 'Payment Proofs',
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
