"""
Chargily Pay checkout tracking + the PaymentState values it needs.

Adds chargily_checkout_id/chargily_checkout_url (set by
orders.chargily.create_checkout_for_order) and widens PaymentState with
PENDING/FAILED/CANCELED/EXPIRED, so a CIB/Edahabia order settling through
Chargily's hosted checkout can be tracked the same way a BaridiMob
transfer already is -- see orders/chargily.py and orders/signals.py for
the webhook-driven transitions between them.

Widening PaymentState's choices rewrites no rows, same as every earlier
choices-only migration on this model (0003, 0004): historic orders keep
rendering whatever they already have, and NOT_REQUIRED/AWAITING_PROOF/
UNDER_REVIEW/CONFIRMED/REJECTED are all still valid values, unchanged.
"""

# Generated by Django 6.1.1 on 2026-09-16 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_baridimob_payment_proof'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='chargily_checkout_id',
            field=models.CharField(blank=True, db_index=True, max_length=64),
        ),
        migrations.AddField(
            model_name='order',
            name='chargily_checkout_url',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_state',
            field=models.CharField(choices=[('not_required', 'Not Required'), ('awaiting_proof', 'Awaiting Payment Proof'), ('under_review', 'Proof Under Review'), ('pending', 'Awaiting Card Payment'), ('confirmed', 'Payment Confirmed'), ('rejected', 'Proof Rejected'), ('failed', 'Card Payment Failed'), ('canceled', 'Card Payment Canceled'), ('expired', 'Checkout Expired')], default='not_required', max_length=20),
        ),
    ]
