# Generated by Django 6.1.1 on 2026-09-17 06:14

import core.constants
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_chargily_card_payment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='delivery_wilaya',
            field=models.CharField(choices=core.constants.wilaya_choices, max_length=2),
        ),
    ]
